[project]
name = "geometry-calculator-backend"
version = "2.1.0"
description = "几何计算器 后端"
#readme = "README.en.md"
requires-python = ">=3.12"
dependencies = [
    "pywebview==5.4",
    "sympy>=1.14.0",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
default = true
